### Home page (200)

GET http://localhost:9242

### API: retrieve one menu item in JSON format (200)

GET http://localhost:9242/api/menu-items/1
Accept: application/json

### API: retrieve one menu item in JSON format (404)

GET http://localhost:9242/api/menu-items/99
Accept: application/json

### API: retrieve one menu item in XML format (200)

GET http://localhost:9242/api/menu-items/1
Accept: application/xml

### API: retrieve one menu item in XML format (404)

GET http://localhost:9242/api/menu-items/99
Accept: application/xml

### API: retrieve all menu items (200)

GET http://localhost:9242/api/menu-items
Accept: application/json

### API: retrieve all chefs of one menu item (200)

GET http://localhost:9242/api/menu-items/1/chefs
Accept: application/json

### API: search menu items (200)

GET http://localhost:9242/api/menu-items/search?search=salad
Accept: application/json

### API: delete a menu items (204)

DELETE http://localhost:9242/api/menu-items/1
Cookie: JSESSIONID=5DF68D1F05485503D2E21C52774058C3
X-CSRF-TOKEN: v3RX2AC1UfpvN0ETXsy9Oo1x_iTgHrP22nZsaI_TbfKBfCkJ2UNvvDiDYMNCU3IjbeGJDugS00WFLovb40VZXOrlX8e5RB47

### API: delete a menu item (403)

DELETE http://localhost:9242/api/menu-items/99
Cookie: JSESSIONID=5DF68D1F05485503D2E21C52774058C3
X-CSRF-TOKEN: v3RX2AC1UfpvN0ETXsy9Oo1x_iTgHrP22nZsaI_TbfKBfCkJ2UNvvDiDYMNCU3IjbeGJDugS00WFLovb40VZXOrlX8e5RB47

### API: add a menu item (201)

POST http://localhost:9242/api/menu-items
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=5DF68D1F05485503D2E21C52774058C3
X-CSRF-TOKEN: v3RX2AC1UfpvN0ETXsy9Oo1x_iTgHrP22nZsaI_TbfKBfCkJ2UNvvDiDYMNCU3IjbeGJDugS00WFLovb40VZXOrlX8e5RB47

{
  "name": "Pizza",
  "price": 10.0,
  "courseName": "Main",
  "vegetarian": false,
  "spiceLvl": 3
}

### API: add a menu item

POST http://localhost:9242/api/menu-items
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=5DF68D1F05485503D2E21C52774058C3
X-CSRF-TOKEN: v3RX2AC1UfpvN0ETXsy9Oo1x_iTgHrP22nZsaI_TbfKBfCkJ2UNvvDiDYMNCU3IjbeGJDugS00WFLovb40VZXOrlX8e5RB47

{
  "name": "",
  "price": -5,
  "courseName": "Main",
  "vegetarian": false,
  "spiceLvl": 3
}

### API: change a menu item (204)

PATCH http://localhost:9242/api/menu-items/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=5DF68D1F05485503D2E21C52774058C3
X-CSRF-TOKEN: v3RX2AC1UfpvN0ETXsy9Oo1x_iTgHrP22nZsaI_TbfKBfCkJ2UNvvDiDYMNCU3IjbeGJDugS00WFLovb40VZXOrlX8e5RB47

{
  "name": "Pizza",
  "price": 10.0,
  "vegetarian": false,
  "spiceLvl": 3
}

### API: change a menu item (404)

PATCH http://localhost:9242/api/menu-items/99
Accept: application/json
Content-Type: application/json

{
  "name": "Pizza",
  "price": 10.0,
  "vegetarian": false,
  "spiceLvl": 3
}

### API: change a menu item

PATCH http://localhost:9242/api/menu-items/1
Accept: application/json
Content-Type: application/json
Cookie: JSESSIONID=5DF68D1F05485503D2E21C52774058C3
X-CSRF-TOKEN: v3RX2AC1UfpvN0ETXsy9Oo1x_iTgHrP22nZsaI_TbfKBfCkJ2UNvvDiDYMNCU3IjbeGJDugS00WFLovb40VZXOrlX8e5RB47

{
  "name": "",
  "price": 10.0,
  "vegetarian": false,
  "spiceLvl": 3
}
