### Home page (200)

GET http://localhost:9242

### API: retrieve one menu item in JSON format (200)

GET http://localhost:9242/api/menu-items/1
Accept: application/json

### API: retrieve one menu item in JSON format (404)

GET http://localhost:9242/api/menu-items/99
Accept: application/json

### API: retrieve one menu item in XML format (200)

GET http://localhost:9242/api/menu-items/1
Accept: application/xml

### API: retrieve one menu item in XML format (404)

GET http://localhost:9242/api/menu-items/99
Accept: application/xml

### API: retrieve all menu items (200)

GET http://localhost:9242/api/menu-items
Accept: application/json

### API: retrieve all chefs of one menu item

GET http://localhost:9242/api/menu-items/1/chef
Accept: application/json

### API: search menu items (204)

GET http://localhost:9242/api/menu-items?search=salad
Accept: application/json

### API: delete a menu items (204)

DELETE http://localhost:9242/api/menu-items/1

### API: delete a menu item (404)

DELETE http://localhost:9242/api/menu-items/99

### API: add a menu item (201)

POST http://localhost:9242/api/menu-items
Accept: application/json
Content-Type: application/json

{
  "name": "Name"
}

### API: add a menu item

POST http://localhost:9242/api/menu-items
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

### API: change a menu item name (204)

PATCH http://localhost:9242/api/menu-items/1
Accept: application/json
Content-Type: application/json

{
  "name": "Pizza"
}

### API: change a menu item name

PATCH http://localhost:9242/api/menu-items/99
Accept: application/json
Content-Type: application/json

{
  "name": "Name"
}

### API: change a menu item name

PATCH http://localhost:9242/api/menu-items/1
Accept: application/json
Content-Type: application/json

{
  "name": ""
}
